compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

nodeLinker: node-modules

npmMinimalAgeGate: '7d'

packageExtensions:
  '@tiptap/react@*':
    dependencies:
      '@floating-ui/dom': '^1.7.4'
